https://github.com/M1sterchamp/PeanFMApplication/blob/main/version.json

FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

EXPOSE 8080

CMD ["python", "app.py"]
